import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    value: 0,
}
// counterReducer is a method that is auto-generated by createSlice
// Reducer - a pure function that decides how the states should be managed based on centain actions. It is a state updater.

// for Interview - A reducer is a function that takes the current state and an action and return a new state.
export const counterSlice = createSlice({
    name: 'counter',
    initialState,
    reducers: {
        increment: (state) => {
            state.value += 1
        },
        decrement: (state) => {
            state.value -= 1
        },
        incrementByAmount: (state, action) => {
            state.value += action.payload
        },
        multiply: (state) => {
            state.value *= 2;
        },
        reset: (state) => {
          state.value = 0;
        }
        
    },
})

export const { increment, decrement, incrementByAmount, multiply, reset } = counterSlice.actions

export default counterSlice.reducer